num_runs: 3
num_cores: 2
num_threads: 128
max_request_queue_length: 250
policy: roundRobin
# policy: fcfs
quantum_size: 0.4
num_users: 2000
# Stopping criterion is the number of requests to generate (need not finish)
stopping_criterion: 200000
context_switch_overhead:  0.005

think_time_distribution:
  name: c+exp
  params:
    c: 1500.0
    lambd: 0.002

service_time_distribution:
  name: exponential
  params:
    lambd: 0.5

timeout_distribution:
  name: c+exp
  params:
    c: 500.0
    lambd: 0.002


# think_time_distribution:
#   name: deterministic
#   params:
#     c: 2000.0

# service_time_distribution:
#   name: deterministic
#   params:
#     c: 2.0

# timeout_distribution:
#   name: deterministic
#   params:
#     c: 1000.0

# think_time_distribution:
#   name: uniform
#   params:
#     a: 1500.0
#     b: 2500.0

# service_time_distribution:
#   name: uniform
#   params:
#     a: 1.0
#     b: 3.0
